[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc = "0.8.13"
optimizer = true
optimizer_runs = 200

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_limit = 9223372036854775807

# Fuzz testing settings
fuzz = { runs = 1000 }

# Invariant testing settings
invariant = { runs = 100, depth = 15 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
fuzz = { runs = 10000 }
verbosity = 4

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
